# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['pyconfigurator']

package_data = \
{'': ['*']}

setup_kwargs = {
    'name': 'pyconfigurator',
    'version': '0.1.0',
    'description': 'Configuration provider wrapper for multiple sources',
    'long_description': '',
    'author': 'gothrek22',
    'author_email': 'gothrek22@gmail.com',
    'maintainer': None,
    'maintainer_email': None,
    'url': 'https://github.com/gothrek22/pyconfigurator',
    'packages': packages,
    'package_data': package_data,
    'python_requires': '>=3.7,<4.0',
}


setup(**setup_kwargs)

# This setup.py was autogenerated using poetry.
